spring.application.name=demo

# ?ы듃 蹂寃??꾩슂??server.port=8080

# jsp ?섍꼍 ?ㅼ젙
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# 404, 500 ?ㅻ쪟 ?섏씠吏 ?ㅼ젙
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=true

# DB ?묒냽 ?ㅼ젙
# spring.datasource.dbcp2.driver-class-name=oracle.jdbc.driver.OracleDriver
# spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
spring.datasource.url=jdbc:log4jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=bbs
spring.datasource.password=bbs

# 荑쇰━ mybatis ?ㅼ젙
mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

# jdbc濡쒓렇 異쒕젰 ?ㅼ젙
# TRACE < DEBUG < INFO < WARN < ERROR < OFF
# SQL 荑쇰━臾몄쓣 肄섏넄 異쒕젰?쒕떎.
logging.level.jdbc.sqlonly=off
# SQL 荑쇰━臾??섑뻾 ?쒓컙
logging.level.jdbc.sqltiming=info 
# SQL 荑쇰━臾?寃곌낵 ?뺤씤
logging.level.jdbc.resultsettable=info
# SQL 荑쇰━ 寃?щ? 濡쒓렇??異쒕젰
logging.level.jdbc.audit=off
# SQL ?곗씠??濡쒓렇
logging.level.jdbc.resultset=off
# SQL ?곌껐 諛??댁젣 ?뺣낫
logging.level.jdbc.connection=off

# 肄섏넄???뺣낫 異붽? ?쒓린
logging.pattern.console=%clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr([rowNumber]: %line){red} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}


# static ?대뜑 ?댁쇅???ㅻⅨ ?대뜑瑜??뺤쟻 由ъ냼??寃쎈줈濡???寃쎌슦
# spring.web.resources.static-locations=classpath:/abcd/
# static ?뚯씪??罹먯떛 湲곌컙 ?ㅼ젙 (1?쒓컙 = 3600)
# spring.web.resources.cache.cachecontrol.max-age=3600

# ?뚯씪 ?ㅼ젙
spring.servlet.multipart.enabled=true
spring.servlet.multipart.location=C:\\multipart\\upload_file\\temp
# ?뚯씪 ?섎굹??理쒕? ?낅줈??媛?ν븳 ?⑸웾
spring.servlet.multipart.max-file-size=100MB
# ?뚯씪 ?щ윭媛쒕? ?낅줈???쒕룄?좊븣 理쒕? ?⑸웾
spring.servlet.multipart.max-request-size=200MB

upload.path=C:\\multipart\\upload_file

